# Generated by Django 4.2.9 on 2024-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.ManyToManyField(null=True, related_name='r_answers', to='base.answers'),
        ),
    ]
