# Generated by Django 4.2.9 on 2024-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_questions_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='r_answers', to='base.answers'),
        ),
    ]
