# Generated by Django 4.2.9 on 2024-09-21 10:17

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_forms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forms',
        ),
        migrations.AddField(
            model_name='questions',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, validators=[base.models.validate_non_negative]),
        ),
    ]
