# Generated by Django 4.2.9 on 2024-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_reports_options_alter_reports_csv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
