# Generated by Django 4.2.9 on 2024-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
