# Generated by Django 4.2.9 on 2024-09-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_results_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='title',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
        migrations.RemoveField(
            model_name='results',
            name='title',
        ),
    ]
