# Generated by Django 4.2.9 on 2024-09-21 17:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_answers_title_remove_questions_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[base.models.validate_higher_value]),
        ),
    ]
