# Generated by Django 4.2.9 on 2024-09-21 17:38

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_answers_priority_results_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[base.models.validate_higher_value, base.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='questions',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[base.models.validate_higher_value, base.models.validate_non_negative]),
        ),
    ]
